sudo: required

language: python

python:
  - "3.9"

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=2.0.0

install:
  - echo "Do nothing"

before_script:
  - pip install docker-compose
  - docker-compose -f docker-compose-dev.yml up --build -d

script:
  - docker-compose -f docker-compose-dev.yml run users_api python manage.py tests
  - docker-compose -f docker-compose-dev.yml run users_api flake8 project

after_script:
  - docker-compose -f docker-compose-dev.yml down