sudo: required

language: python

python:
  - "3.9"

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 2.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-darwin-arm64 > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-copmose /usr/local/bin

before_script:
  - docker-compose -f docker-compose-dev.yml up --build -d

script:
  - docker-compose -f docker-compose-dev.yml run users_api python manage.py tests
  - docker-compose -f docker-compose-dev.yml run users_api flake8 project

after_script:
  - docker-compose -f docker-compose-dev.yml down