FROM python:3.9

RUN apt-get update -y -qq \
  && apt-get install -y -qq --no-install-recommends \
    netcat \
  && apt-get -q clean

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./requirements-dev.txt /usr/src/app/requirements-dev.txt
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

RUN pip install -r requirements-dev.txt --quiet

COPY . /usr/src/app

CMD ["bash", "./entrypoint.sh"]
