FROM python:3.9
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./requirements-dev.txt /usr/src/app/requirements-dev.txt
RUN pip install -r requirements-dev.txt
COPY . /usr/src/app
CMD python manage.py run -h 0.0.0.0
