version: '3'
services:
  users_api:
    container_name: users_api
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@user-db:5432/user_prod
      - DATABASE_TEST_URL=postgresql://postgres:postgres@user-db:5432/user_test
    depends_on:
      - users_db
    links:
      - users_db

  users_db:
    container_name: users_db
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_prod
      - POSTGRES_PASSWORD=postgres_prod
