FROM python:3.9

RUN apt-get update -y -qq \
  && apt-get install -y -qq --no-install-recommends \
    netcat \
  && apt-get -q clean

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./requirements-prod.txt /usr/src/app/requirements-prod.txt
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh

RUN pip install -r requirements-prod.txt --quiet

COPY . /usr/src/app

CMD ["bash", "./entrypoint-prod.sh"]
